In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("resultados_tsp_fase_3.csv")

In [4]:
df_sort = df.sort_values(by="Mejor_Fitness", ascending=True)

In [8]:
df_sort.head(20)

,Configuracion,Cruza,Mutacion,Tasa_mutacion,Tam_poblacion,Ejecución No.,Elitismo,Mejor_Fitness,Diversidad_Final
530,cruce_bordes | mutacion_intercambio | mut:0.2 ...,cruce_bordes,mutacion_intercambio,0.20,200,20,False,66633.436113,0.073947
497,cruce_bordes | mutacion_intercambio | mut:0.2 ...,cruce_bordes,mutacion_intercambio,0.20,100,17,False,66633.436113,0.052105
44,cruce_bordes | mutacion_intercambio | mut:0.05...,cruce_bordes,mutacion_intercambio,0.05,100,14,True,66633.436113,0.012105
39,cruce_bordes | mutacion_intercambio | mut:0.05...,cruce_bordes,mutacion_intercambio,0.05,100,9,True,66633.436113,0.016842
245,cruce_bordes | mutacion_intercambio | mut:0.2 ...,cruce_bordes,mutacion_intercambio,0.20,200,5,True,66633.436113,0.057105
250,cruce_bordes | mutacion_intercambio | mut:0.2 ...,cruce_bordes,mutacion_intercambio,0.20,200,10,True,66633.436113,0.061842
243,cruce_bordes | mutacion_intercambio | mut:0.2 ...,cruce_bordes,mutacion_intercambio,0.20,200,3,True,66633.436113,0.065789
241,cruce_bordes | mutacion_intercambio | mut:0.2 ...,cruce_bordes,mutacion_intercambio,0.20,200,1,True,66633.436113,0.085789
63,cruce_bordes | mutacion_intercambio | mut:0.05...,cruce_bordes,mutacion_intercambio,0.05,200,3,True,66633.436113,0.017895
268,cruce_bordes | mutacion_intercambio | mut:0.2 ...,cruce_bordes,mutacion_intercambio,0.20,200,28,True,66633.436113,0.089474
267,cruce_bordes | mutacion_intercambio | mut:0.2 ...,cruce_bordes,mutacion_intercambio,0.20,200,27,True,66633.436113,0.071579
60,cruce_bordes | mutacion_intercambio | mut:0.05...,cruce_bordes,mutacion_intercambio,0.05,200,0,True,66633.436113,0.010526
54,cruce_bordes | mutacion_intercambio | mut:0.05...,cruce_bordes,mutacion_intercambio,0.05,100,24,True,66633.436113,0.011579
473,cruce_bordes | mutacion_intercambio | mut:0.2 ...,cruce_bordes,mutacion_intercambio,0.20,50,23,False,66633.436113,0.078421
254,cruce_bordes | mutacion_intercambio | mut:0.2 ...,cruce_bordes,mutacion_intercambio,0.20,200,14,True,66633.436113,0.055789
253,cruce_bordes | mutacion_intercambio | mut:0.2 ...,cruce_bordes,mutacion_intercambio,0.20,200,13,True,66633.436113,0.041842
265,cruce_bordes | mutacion_intercambio | mut:0.2 ...,cruce_bordes,mutacion_intercambio,0.20,200,25,True,66633.436113,0.058684
70,cruce_bordes | mutacion_intercambio | mut:0.05...,cruce_bordes,mutacion_intercambio,0.05,200,10,True,66633.436113,0.009474
83,cruce_bordes | mutacion_intercambio | mut:0.05...,cruce_bordes,mutacion_intercambio,0.05,200,23,True,66633.436113,0.008947
437,cruce_bordes | mutacion_intercambio | mut:0.1 ...,cruce_bordes,mutacion_intercambio,0.10,200,17,False,66633.436113,0.044211

In [10]:
df_result = df_sort.head()

In [11]:
df_result

,Configuracion,Cruza,Mutacion,Tasa_mutacion,Tam_poblacion,Ejecución No.,Elitismo,Mejor_Fitness,Diversidad_Final
3758,cruce_bordes | mutacion_desordenada | mut:0.2 ...,cruce_bordes,mutacion_desordenada,0.2,200,8,False,66633.436113,0.113947
5856,cruce_orden | mutacion_desordenada | mut:0.2 |...,cruce_orden,mutacion_desordenada,0.2,50,6,False,66633.436113,0.153421
2554,cruce_bordes | mutacion_intercambio | mut:0.1 ...,cruce_bordes,mutacion_intercambio,0.1,100,4,False,66633.436113,0.034211
1717,cruce_pmx | mutacion_inversion | mut:0.1 | pob...,cruce_pmx,mutacion_inversion,0.1,50,7,True,66633.436113,0.018947
944,cruce_pmx | mutacion_insercion | mut:0.1 | pob...,cruce_pmx,mutacion_insercion,0.1,100,14,False,66633.436113,0.041579

In [12]:
df_result.to_latex("Resultado_todos.tex", columns=["Cruza", "Mutacion", "Tasa_mutacion", "Tam_poblacion", "Elitismo", "Mejor_Fitness", "Diversidad_Final"])