In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("resultados_experimentos_neat_fase_3.csv")

In [2]:
df

,Dimensiones,Representacion,Fitness_Evolutivo,F1_Test,Nodos_Finales,Conexiones_Finales,pop_size,node_add_prob,conn_add_prob,conn_delete_prob,compatibility_threshold,weight_mutate_rate,survival_threshold,num_inputs
0,0.3,WE,0.627215,0.407514,3,162,400,0.1,0.1,0.1,2.5,0.5,0.2,270
1,0.3,WE,0.610431,0.423132,3,162,400,0.1,0.1,0.1,2.5,0.5,0.3,270
2,0.3,WE,0.550001,0.374456,4,162,400,0.1,0.1,0.1,2.5,0.5,0.5,270
3,0.3,WE,0.632685,0.410691,3,163,400,0.1,0.1,0.1,2.5,0.7,0.2,270
4,0.3,WE,0.573999,0.425482,3,161,400,0.1,0.1,0.1,2.5,0.7,0.3,270
5,0.3,WE,0.527261,0.365622,5,167,400,0.1,0.1,0.1,2.5,0.7,0.5,270
6,0.3,WE,0.607199,0.453365,4,162,400,0.1,0.1,0.1,2.5,0.9,0.2,270
7,0.3,WE,0.602673,0.383221,3,162,400,0.1,0.1,0.1,2.5,0.9,0.3,270
8,0.3,WE,0.588574,0.459666,3,160,400,0.1,0.1,0.1,2.5,0.9,0.5,270
9,0.3,WE,0.621264,0.424550,4,162,400,0.1,0.1,0.1,3.0,0.5,0.2,270
10,0.3,WE,0.580063,0.419472,3,162,400,0.1,0.1,0.1,3.0,0.5,0.3,270
11,0.3,WE,0.530801,0.423090,3,162,400,0.1,0.1,0.1,3.0,0.5,0.5,270
12,0.3,WE,0.586582,0.365459,3,165,400,0.1,0.1,0.1,3.0,0.7,0.2,270
13,0.3,WE,0.565117,0.465655,4,163,400,0.1,0.1,0.1,3.0,0.7,0.3,270
14,0.3,WE,0.544346,0.408047,5,165,400,0.1,0.1,0.1,3.0,0.7,0.5,270
15,0.3,WE,0.564197,0.385663,3,161,400,0.1,0.1,0.1,3.0,0.9,0.2,270
16,0.3,WE,0.586644,0.437078,3,162,400,0.1,0.1,0.1,3.0,0.9,0.3,270
17,0.3,WE,0.495350,0.399900,3,161,400,0.1,0.1,0.1,3.0,0.9,0.5,270
18,0.3,WE,0.575957,0.490991,4,162,400,0.1,0.1,0.1,5.0,0.5,0.2,270
19,0.3,WE,0.570316,0.382811,3,157,400,0.1,0.1,0.1,5.0,0.5,0.3,270
20,0.3,WE,0.541790,0.471703,3,161,400,0.1,0.1,0.1,5.0,0.5,0.5,270
21,0.3,WE,0.590684,0.398515,4,166,400,0.1,0.1,0.1,5.0,0.7,0.2,270
22,0.3,WE,0.532190,0.410658,3,163,400,0.1,0.1,0.1,5.0,0.7,0.3,270
23,0.3,WE,0.537889,0.403572,3,164,400,0.1,0.1,0.1,5.0,0.7,0.5,270
24,0.3,WE,0.589111,0.394824,3,155,400,0.1,0.1,0.1,5.0,0.9,0.2,270
25,0.3,WE,0.548518,0.452150,3,161,400,0.1,0.1,0.1,5.0,0.9,0.3,270
26,0.3,WE,0.547264,0.410482,7,171,400,0.1,0.1,0.1,5.0,0.9,0.5,270

In [3]:
df_sort = df.sort_values(by="F1_Test", ascending=False)
df_sort.head()

,Dimensiones,Representacion,Fitness_Evolutivo,F1_Test,Nodos_Finales,Conexiones_Finales,pop_size,node_add_prob,conn_add_prob,conn_delete_prob,compatibility_threshold,weight_mutate_rate,survival_threshold,num_inputs
18,0.3,WE,0.575957,0.490991,4,162,400,0.1,0.1,0.1,5.0,0.5,0.2,270
20,0.3,WE,0.541790,0.471703,3,161,400,0.1,0.1,0.1,5.0,0.5,0.5,270
13,0.3,WE,0.565117,0.465655,4,163,400,0.1,0.1,0.1,3.0,0.7,0.3,270
8,0.3,WE,0.588574,0.459666,3,160,400,0.1,0.1,0.1,2.5,0.9,0.5,270
6,0.3,WE,0.607199,0.453365,4,162,400,0.1,0.1,0.1,2.5,0.9,0.2,270

In [5]:
df_final = df_sort.head()
df_final.to_latex('Resultados_fase_2.tex', columns=["Representacion", "Dimensiones", "Fitness_Evolutivo", "F1_Test", "Nodos_Finales", "Conexiones_Finales", "pop_size"])

In [4]:
df_final = df_sort.head()
df_final.to_latex('Resultados_fase_3.tex', columns=["compatibility_threshold", "weight_mutate_rate", "survival_threshold", "Fitness_Evolutivo", "F1_Test"])