In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv("resultados_experimentos_neat_fase_2.csv")

In [3]:
df

,Dimensiones,Representacion,Fitness_Evolutivo,F1_Test,Nodos_Finales,Conexiones_Finales,pop_size,node_add_prob,conn_add_prob,conn_delete_prob,compatibility_threshold,weight_mutate_rate,survival_threshold,num_inputs
0,0.3,WE,0.556426,0.392122,3,161,400,0.1,0.05,0.05,2.5,0.5,0.5,270
1,0.3,WE,0.561194,0.366357,5,166,400,0.1,0.05,0.10,2.5,0.5,0.5,270
2,0.3,WE,0.565151,0.415199,4,159,400,0.1,0.05,0.20,2.5,0.5,0.5,270
3,0.3,WE,0.583833,0.416748,3,162,400,0.1,0.10,0.05,2.5,0.5,0.5,270
4,0.3,WE,0.566903,0.455585,4,165,400,0.1,0.10,0.10,2.5,0.5,0.5,270
5,0.3,WE,0.550051,0.366159,3,158,400,0.1,0.10,0.20,2.5,0.5,0.5,270
6,0.3,WE,0.568316,0.369404,3,163,400,0.1,0.20,0.05,2.5,0.5,0.5,270
7,0.3,WE,0.568128,0.391198,3,164,400,0.1,0.20,0.10,2.5,0.5,0.5,270
8,0.3,WE,0.572166,0.391879,4,160,400,0.1,0.20,0.20,2.5,0.5,0.5,270
9,0.3,WE,0.562831,0.420241,4,163,400,0.2,0.05,0.05,2.5,0.5,0.5,270
10,0.3,WE,0.544470,0.420809,4,161,400,0.2,0.05,0.10,2.5,0.5,0.5,270
11,0.3,WE,0.541947,0.408554,3,162,400,0.2,0.05,0.20,2.5,0.5,0.5,270
12,0.3,WE,0.568759,0.393642,3,162,400,0.2,0.10,0.05,2.5,0.5,0.5,270
13,0.3,WE,0.577803,0.395089,4,162,400,0.2,0.10,0.10,2.5,0.5,0.5,270
14,0.3,WE,0.551996,0.394177,6,167,400,0.2,0.10,0.20,2.5,0.5,0.5,270
15,0.3,WE,0.546611,0.408747,4,164,400,0.2,0.20,0.05,2.5,0.5,0.5,270
16,0.3,WE,0.530126,0.443895,5,169,400,0.2,0.20,0.10,2.5,0.5,0.5,270
17,0.3,WE,0.544243,0.332855,5,163,400,0.2,0.20,0.20,2.5,0.5,0.5,270
18,0.3,WE,0.566666,0.409299,5,165,400,0.3,0.05,0.05,2.5,0.5,0.5,270
19,0.3,WE,0.596084,0.449262,7,171,400,0.3,0.05,0.10,2.5,0.5,0.5,270
20,0.3,WE,0.573450,0.436380,10,172,400,0.3,0.05,0.20,2.5,0.5,0.5,270
21,0.3,WE,0.534268,0.402294,6,168,400,0.3,0.10,0.05,2.5,0.5,0.5,270
22,0.3,WE,0.538731,0.398704,4,164,400,0.3,0.10,0.10,2.5,0.5,0.5,270
23,0.3,WE,0.526266,0.398647,8,171,400,0.3,0.10,0.20,2.5,0.5,0.5,270
24,0.3,WE,0.567740,0.428653,5,168,400,0.3,0.20,0.05,2.5,0.5,0.5,270
25,0.3,WE,0.540798,0.400027,5,165,400,0.3,0.20,0.10,2.5,0.5,0.5,270
26,0.3,WE,0.566424,0.414157,7,174,400,0.3,0.20,0.20,2.5,0.5,0.5,270

In [4]:
df_sort = df.sort_values(by="F1_Test", ascending=False)
df_sort.head()

,Dimensiones,Representacion,Fitness_Evolutivo,F1_Test,Nodos_Finales,Conexiones_Finales,pop_size,node_add_prob,conn_add_prob,conn_delete_prob,compatibility_threshold,weight_mutate_rate,survival_threshold,num_inputs
4,0.3,WE,0.566903,0.455585,4,165,400,0.1,0.10,0.10,2.5,0.5,0.5,270
19,0.3,WE,0.596084,0.449262,7,171,400,0.3,0.05,0.10,2.5,0.5,0.5,270
16,0.3,WE,0.530126,0.443895,5,169,400,0.2,0.20,0.10,2.5,0.5,0.5,270
20,0.3,WE,0.573450,0.436380,10,172,400,0.3,0.05,0.20,2.5,0.5,0.5,270
24,0.3,WE,0.567740,0.428653,5,168,400,0.3,0.20,0.05,2.5,0.5,0.5,270

In [5]:
df_final = df_sort.head()
df_final.to_latex('Resultados_fase_2.tex', columns=["Representacion", "Dimensiones", "Fitness_Evolutivo", "F1_Test", "Nodos_Finales", "Conexiones_Finales", "pop_size"])

In [7]:
df_final = df_sort.head()
df_final.to_latex('Resultados_fase_2.tex', columns=["node_add_prob", "conn_add_prob", "conn_delete_prob", "Fitness_Evolutivo", "F1_Test"])